fix web stuff to work with new config

diff --git a/bin/cherryserver b/bin/cherryserver
--- a/bin/cherryserver
+++ b/bin/cherryserver
@@ -1,8 +1,24 @@
 #!/bin/bash
 
-source $HOME/.netqualrc
+dir=$(dirname $0)
+source "$dir/lib.sh"
+
+if [ "$#" != "1" ]; then
+	echo "Usage: $0 CONFIG_DIR" >/dev/stderr
+	exit 1
+fi
+
+export NQ_CONFIG_DIR="$1"
+
+config_file=$(get_config_file)
+
+if ! source "$config_file";
+then
+	echo "failed to source config file" >/dev/stderr
+	exit 1
+fi
 
 export DB_DIR
-export CONFIG_DIR
+export CONFIG_DIR="$NQ_CONFIG_DIR"
 
 python cherryserver.py
